/*
 * Name: irq_pit.c
 * Author: Martin Stankus
 *
 */

#include "MKL25Z4.h"

#include "soc_def.h"
#include "res_alloc.h"

#include "wdog.h"

#define LEDR_PIT_CHAN	0u
#define LEDG_PIT_CHAN	1u

#define LEDR_PERIOD		24000000ul
#define LEDG_PERIOD		18000000ul

#define PIT_EXPT_PRI	2u

void __attribute__ ((interrupt)) PIT_IRQHandler(void)
{
	if (PIT->CHANNEL[LEDR_PIT_CHAN].TFLG & PIT_TFLG_TIF_MASK) {
		PIT->CHANNEL[LEDR_PIT_CHAN].TFLG = PIT_TFLG_TIF_MASK;
		GPIO_LEDR->PTOR = IOMASK_LEDR;
	}

	if (PIT->CHANNEL[LEDG_PIT_CHAN].TFLG & PIT_TFLG_TIF_MASK) {
		PIT->CHANNEL[LEDG_PIT_CHAN].TFLG = PIT_TFLG_TIF_MASK;
		GPIO_LEDG->PTOR = IOMASK_LEDG;
	}
}

int main(void)
{
	wdog_init(WDOG_CONF_LPOCLK_1024_CYCLES);

	GPIO_LEDR->PDDR |= IOMASK_LEDR;
	PORT_LEDR->PCR[IOIND_LEDR] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);

	GPIO_LEDG->PDDR |= IOMASK_LEDG;
	PORT_LEDG->PCR[IOIND_LEDG] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);

	NVIC_SetPriority(PIT_IRQn, PIT_EXPT_PRI);
	NVIC_EnableIRQ(PIT_IRQn);

	PIT->MCR = PIT_MCR_FRZ_MASK;
	PIT->CHANNEL[LEDR_PIT_CHAN].LDVAL = LEDR_PERIOD - 1u;
	PIT->CHANNEL[LEDG_PIT_CHAN].LDVAL = LEDG_PERIOD - 1u;
	PIT->CHANNEL[LEDR_PIT_CHAN].TCTRL = PIT_TCTRL_TIE_MASK | PIT_TCTRL_TEN_MASK;
	PIT->CHANNEL[LEDG_PIT_CHAN].TCTRL = PIT_TCTRL_TIE_MASK | PIT_TCTRL_TEN_MASK;

	while (1) {
		wdog_refresh();
	}

	return 0;
}
